USE `dragonball`;

INSERT INTO `combates` VALUES (1,'Jackie Chun','Goku vs Jackie Chun'),(2,'Goku','Goku vs Tao Pai Pai'),(3,'Goku','Goku vs Piccolo Daimao'),(4,'Empate','Goku vs Vegeta'),(5,'Goku','Goku vs Freezer'),(6,'Vegeta','Vegeta vs Zarbon'),(7,'Gohan','Gohan vs Cell'),(8,'Cell','Goku vs Cell'),(9,'Majin Vegeta','Goku vs Majin Vegeta'),(10,'Goku','Goku vs Kid Buu'),(11,'Goku','Goku vs Baby Vegeta'),(12,'Goku','Goku vs Super 17'),(13,'Goku','Goku vs Shenron de 1 Estrella'),(14,'Bills ','Goku vs Bills'),(15,'Goku','Goku vs Golden Freezer'),(16,'Vegeta','Vegeta vs Hit'),(17,'Empate','Goku vs Hit'),(18,'Goku','Goku vs Jiren'),(19,'Vegeta','Vegeta vs Toppo'),(20,'Gogeta','Gogeta vs Broly');

INSERT INTO `objetos` VALUES (1,'Esferas del Dragón','Mágico'),(2,'Semilla de Ermitaño','Alimento Regenerico'),(3,'Bastón Mágico','Mágico'),(4,'Nube Voladora','Mágico'),(5,'Radar del Dragón','Tecnológico'),(6,'Espada Z','Arma'),(7,'Cápsulas Hoi-Poi','Tecnológico'),(8,'Armadura Saiyan','Armadura'),(9,'Scouter','Tecnológico'),(10,'Potaras','Tecnológico'),(11,'Espada de Trunks','Arma'),(12,'Bola de Poder','Mágico'),(13,'Cámara del Tiempo Hiperbólica','Tecnológico'),(14,'Cápsula Espacial Saiyan','Nave'),(15,'Bastón de Karin','Mágico'),(16,'Anillo del Tiempo','Mágico'),(17,'Máquina del Tiempo','Tecnológico'),(18,'Cuerpo de Frío','Transporte'),(19,'Botellas de Mafuba','Mágico'),(20,'Anillo de Fusion','Mágico');

INSERT INTO `organizaciones` VALUES (1,'Ejército Red Ribbon','Militar/Criminal'),(2,'Fuerza Ginyu','Militar'),(3,'Patrulla Galáctica','Fuerza Policial'),(4,'Capsule Corporation','Corporación Tecnológica'),(5,'Guerreros Z','Defensa Planetaria'),(6,'Patrulla del Tiempo','Policía del Tiempo'),(7,'Los Kaioshin','Autoridad Divina'),(8,'Escuela Tortuga','Artes Marciales'),(9,'Escuela Grulla','Artes Marciales'),(10,'Ejército Saiyan','Militar'),(11,'Organización de los Dragones Oscuros','Fuerzas Antagonistas'),(12,'Patrulla del Gran Saiyaman','Superhéroes'),(13,'Ejército de Freezer','Militar'),(14,'La Liga de los Dioses de la Destrucción','Organización Divina'),(15,'La Patrulla de Monjes de Karin','Organización Religiosa'),(16,'Organización Científica del Dr. Gero','Grupo Científico'),(17,'El Clan Demonio de Piccolo Daimao','Organización Criminal'),(18,'Los Heaters','Familia Criminal'),(19,'Los Ángeles','Seres Divinos'),(20,'Los Caballeros del Orgullo','Superhéroes');

INSERT INTO `películas` VALUES (1,'La leyenda del dragón Shenlong',1986),(2,'La Bella Durmiente en el Castillo del Mal',1987),(3,'Aventura mística ',1988),(4,'El camino hacia el más fuerte',1996),(5,'La batalla de los dioses',2013),(6,'La resurrección de Freezer',2015),(7,'Dead Zone',1989),(8,'El más fuerte del mundo',1990),(9,'La super batalla',1990),(10,'El super saiyajin Son Goku ',1991),(11,'Los mejores rivales',1991),(12,'El más poderoso contra el más poderoso',1991),(13,' Guerreros de fuerza ilimitada',1992),(14,'La pelea de los tres saiyajins',1992),(15,'La fusión de Goku y Vegeta',1995),(16,'El ataque del dragón',1995),(17,'El poder invencible',1993),(18,'El regreso de Broly',1994),(19,'Bio Broly',1994),(20,'Super Hero',2022);

INSERT INTO `personajes` VALUES (1,'Goku',1,5,3),(2,'Vegeta',1,5,3),(3,'Piccolo',2,5,2),(4,'Gohan ',1,5,1),(5,'Krillin',3,5,1),(6,'Trunks',1,5,1),(7,'Bulma',3,4,1),(8,'Freezer',4,13,5),(9,'Cell',20,2,5),(10,'Majin Buu',5,5,3),(11,'Broly',1,5,3),(12,'Androide 17',6,16,1),(13,'Androide 16',6,16,1),(14,'Tien Shinhan',3,5,1),(15,'Yamcha',3,5,1),(16,'Beerus',9,14,7),(17,'Whis',9,14,7),(18,'Zamasu',19,14,7),(19,'Jiren',9,20,7),(20,'Zarbon',9,13,5);

INSERT INTO `planetas` VALUES (1,'Tierra','Habitable',80),(2,'Planeta Namek','Habitable',60),(3,'Planeta Vegeta','Guerrero',70),(4,'Planeta Yardrat','Tecnológico',60),(5,'Planeta Freezer N° 79','Militar',80),(6,'Planeta Vampa','Desertico',15),(7,'Planeta Beerus','Divino',90),(8,'Planeta Kaio','Divino',80),(9,'Planeta Kanassa','Conquistador',40),(10,'Planeta Cereal','Colonizado',30),(11,'Planeta Metamor','Habitable',70),(12,'Planeta Zun','Habitable',60),(13,'Planeta Sadala','Guerrero',70),(14,'Planeta Plant','Habitable',80),(15,'Planeta Namek Nuevo','Habitable',70),(16,'Planeta Pital','Médico',60),(17,'Planeta Toffol','Comercial',70),(18,'Planeta Makyo','Demoniaco',50),(19,'Planeta Arlia','Devastado',10),(20,'Planeta Konats','Habitable',80);

INSERT INTO `raza` VALUES (1,'Saiyans'),(2,'Namekainos'),(3,'Terricolas'),(4,'Freezer Race'),(5,'Majin'),(6,'Androides'),(7,'Tuffles'),(8,'Kaioshins'),(9,'Dioses de la Destrucción'),(10,'Yardratianos'),(11,'Heeters'),(12,'Zarbon’s Race'),(13,'Makyanos'),(14,'Konatsianos'),(15,'Arcosianos'),(16,'Demonios del Frío'),(17,'Cerealianos'),(18,'Metamorianos'),(19,'Shin-jin'),(20,'Bio-guerreros');

INSERT INTO `sagas` VALUES (1,'Saga de Pilaf','Pilaf'),(2,'Saga del 21° Torneo de Artes Marciales','Jackie Chun'),(3,'Saga del Ejército Red Ribbon','Ejército Red Ribbon'),(4,'Saga de Baba la Adivina','Baba la adivina'),(5,'Saga de Tien Shinhan','Tien Shinhan'),(6,'Saga de Piccolo Daimao','Piccolo Daimao'),(7,'Saga del 23° Torneo de Artes Marciales','Piccolo jr'),(8,'Saga de los Saiyajin','Raditz'),(9,'Saga de Freezer','Freezer'),(10,'Saga de los Androides','Androides 16 y 17'),(11,'Saga de Cell','Cell'),(12,'Saga de Majin Buu','Majin Buu'),(13,'Saga de los Dragones Oscuros','Dragones malignos'),(14,'Saga de la Batalla de los Dioses','Beerus'),(15,'Saga del Renacimiento de Freezer','Freezer'),(16,'Saga del Torneo de Champa','Champa'),(17,'Saga de Goku Black y Zamasu','Goku black'),(18,'Saga del Torneo del Poder','Jiren'),(19,'Saga de Moro','Moro'),(20,'Saga de Granola','Granola');

INSERT INTO `transformaciones` VALUES (1,'Super sayayin','Emocion intensa','Aumento drástico en poder, velocidad y energía.',1),(2,'Super Saiyajin 2','	Dominio del Super Saiyajin, enojo extremo.','Aumento adicional en poder, más energía y un aura eléctrica.',1),(3,'Super Saiyajin 3','Dominio del Super Saiyajin 2, gran consumo de energía.','Poder masivo y cabello largo, aumenta significativamente el poder.',1),(4,'Super Saiyajin God','Ritual de 5 Saiyajins, puro corazón.',' corazón.	Gran aumento de poder, habilidades divinas.',1),(5,'Super Saiyajin Blue','Dominio del Super Saiyajin God, entrenamiento intenso.','Poder combinado de Super Saiyajin y divinidad.',1),(6,'Ultra instinto','Entrenamiento intenso, autoconocimiento.','Reacciones automáticas, velocidad y evasión.',1),(7,'Ultra instinto dominado','Dominar el ultra instinto','Aumento extremo en poder, velocidad y técnica.',1),(8,'Transformación de Freezer','Entrenamiento intenso, control de su poder.','Aumento de poder, velocidad, y resistencia.',4),(9,'Golden Freezer','Entrenamiento después de la derrota.','Poder abrumador, velocidad y resistencia aumentadas.',4),(10,'Fusión Metamoru','Danza de fusión o técnica de fusión','Combina habilidades, poder y energía de dos guerreros.',18),(11,'Fusión Potara','Uso de pendientes Potara.','Poder combinado, habilidades y técnicas de ambos.',15),(12,'Majin','Ser poseído por Babidi.','Aumenta el poder, agresividad y habilidades.',5),(13,'Super Buu','Consumir a Gotenks y Piccolo.','	Aumento de poder, habilidades de los absorbidos.',5),(14,'Kid Buu','Estado original de Majin Buu.','	Poder caótico y destructivo, habilidades regenerativas.',5),(15,'Transformación de Cell','Absorber a Androide 17 y 18.','Poder combinado, habilidades de los absorbidos.',20),(16,'Perfect Cell','Completar la absorción de los androides.','Máximo poder y resistencia, habilidades avanzadas.',20),(17,'Super Saiyajin Legendario','Presencia de una gran cantidad de energía Saiyajin.','Aumento de poder y agresividad, características únicas.',1),(18,'Demonios del Infierno','Ser un demonio o recibir poder oscuro.','Aumento de poder y habilidades sobrenaturales.',16),(19,'Kaioken','Uso de energía vital, entrenamiento intenso.','Aumento de poder temporal, riesgo para el cuerpo.',1),(20,'Transformación de Broly','Poder de Saiyajin, emoción intensa.','Aumento de poder y fuerza, transformación en guerrero berserker.',1);

INSERT INTO `técnicas` VALUES (1,'Kamehameha','Energía'),(2,'Final flash','Energía'),(3,'Big bang attack','Energía'),(4,'Masenko','Energía'),(5,'Special beam canon','Energía'),(6,'Galick gun','Energía'),(7,'Destructo disc','Energía'),(8,'Genki Dama','Energía'),(9,'Taiyoken','Distracción'),(10,'Instant Transmission','Teletransporte'),(11,'Kikoho','Ki'),(12,'Hellzone Grenade','Ki'),(13,'Final Kamehameha','Ki'),(14,'Burning Attack','Ki'),(15,'Death Beam','Ki'),(16,'Death Ball','Ki'),(17,'Hakai','Destrucción'),(18,'Kaioken','Aumento'),(19,'Fusion Dance','Fusión'),(20,'Evil Containment Wave','Sellado');
